Tiago utilizou a normalização para transformar um arquivo JSON aninhado em um DataFrame no ambiente Python. Contudo, ele percebeu que o separador padrão ('.') nos nomes das colunas criadas a partir dos dados aninhados não atende às suas necessidades.

Tiago gostaria de usar o caractere '_' como separador, resultando em nomes de colunas como cliente_id_cliente, cliente_nome_cliente, compra_id_produto e compra_nome_produto. Como Tiago pode alterar o separador de colunas para '_' ao realizar a normalização?

In [1]:
import pandas as pd
import requests
from http import HTTPStatus

In [6]:
r = requests.get('https://cdn3.gnarususercontent.com.br/4416-python-normalizando-arquivos-json/Projeto/Arquivos%20de%20atividades/questao_5.json')

if r.status_code == HTTPStatus.OK:
    data = r.json()
    df = pd.json_normalize(data, sep="_")
df

,id_pedido,data_pedido,status,cliente_id_cliente,cliente_nome_cliente,compra_id_produto,compra_nome_produto,compra_categoria,compra_quantidade,compra_preco_unitario,compra_preco_total
0,26,2025-01-26,Entregue,126,Zeca Costa,226,Cadeira de Escritório,Móveis,1,550.0,550.0
1,27,2025-01-27,Pendente,127,Amanda Melo,227,Colar de Prata,Acessórios,1,120.0,120.0
2,28,2025-01-28,Entregue,128,Bruna Santos,228,Fogão 4 Bocas,Eletrodomésticos,1,1200.0,1200.0
3,29,2025-01-29,Cancelado,129,Carlos Silva,229,Geladeira,Eletrodomésticos,1,3500.0,3500.0
4,30,2025-01-30,Entregue,130,Débora Lima,230,Teclado Mecânico,Eletrônicos,1,300.0,300.0