Thais utilizou a função pd.read_json para carregar um arquivo JSON recebido em sua empresa. No entanto, ela notou que não conseguia acessar corretamente todos os dados do arquivo no DataFrame.

Um problema identificado foi que a coluna detalhes_compra apresentava informações importantes em formato de dicionário, dificultando a manipulação dos dados:


Ajude Thais a acessar todas as colunas e informações disponíveis nos dados

In [29]:
import pandas as pd
import requests
from http import HTTPStatus

In [32]:
r = requests.get('https://cdn3.gnarususercontent.com.br/4416-python-normalizando-arquivos-json/Projeto/Arquivos%20de%20atividades/questao_3.json')

if r.status_code == HTTPStatus.OK:
    data = r.json()
    df = pd.json_normalize(
        data
    )
df

,id_pedido,id_cliente,nome_cliente,data_pedido,status,detalhes_compra.id_produto,detalhes_compra.nome_produto,detalhes_compra.categoria,detalhes_compra.quantidade,detalhes_compra.preco_unitario,detalhes_compra.preco_total
0,16,116,Paulo Barros,2025-01-16,Pendente,216,Câmera Digital,Eletrônicos,1,2000.0,2000.0
1,17,117,Quezia Fernandes,2025-01-17,Entregue,217,Bolsa de Couro,Acessórios,1,400.0,400.0
2,18,118,Rafael Cardoso,2025-01-18,Cancelado,218,Livro de Ficção,Livros,2,35.0,70.0
3,19,119,Sofia Ribeiro,2025-01-19,Entregue,219,Perfume,Beleza,1,180.0,180.0
4,20,120,Tiago Moraes,2025-01-20,Entregue,220,Guarda-Chuva,Acessórios,1,50.0,50.0