João possui um arquivo JSON contendo dados sobre as vendas da loja onde trabalha, salvo em sua máquina. Ele deseja processar esse arquivo no Python utilizando a biblioteca Pandas.

Ajude João a criar um código que carregue o arquivo JSON como um DataFrame.

In [3]:
import pandas as pd
import requests
from http import HTTPStatus

In [8]:
r = requests.get('https://cdn3.gnarususercontent.com.br/4416-python-normalizando-arquivos-json/Projeto/Arquivos%20de%20atividades/questao_1.json')

if r.status_code == HTTPStatus.OK:
  df = pd.DataFrame(r.json())

df.head()

,id_pedido,id_cliente,nome_cliente,id_produto,nome_produto,categoria,quantidade,preco_unitario,preco_total,data_pedido,status
0,1,101,Alice Silva,201,Camiseta Básica,Roupas,2,50.0,100.0,2025-01-01,Entregue
1,2,102,Bruno Souza,202,Tênis Esportivo,Calçados,1,200.0,200.0,2025-01-02,Pendente
2,3,103,Carla Pereira,203,Relógio Digital,Acessórios,1,150.0,150.0,2025-01-03,Entregue
3,4,104,Daniel Oliveira,204,Calça Jeans,Roupas,2,120.0,240.0,2025-01-04,Cancelado
4,15,115,Olivia Rocha,215,Tênis Casual,Calçados,1,220.0,220.0,2025-01-15,Entregue