Fábio recebeu um conjunto de dados relacionados às vendas da empresa onde trabalha. Ao inspecionar o arquivo, percebeu que se tratava de um JSON com uma estrutura aninhada de 3 níveis.


Como Fábio nunca trabalhou com a normalização de arquivos JSON, ele não sabe como lidar com um arquivo aninhado dessa complexidade. O que Fábio pode fazer para transformar esse JSON em um conjunto de dados utilizável?

In [1]:
import pandas as pd
import requests
from http import HTTPStatus

In [9]:
r = requests.get('https://cdn3.gnarususercontent.com.br/4416-python-normalizando-arquivos-json/Projeto/Arquivos%20de%20atividades/questao_4.json')

if r.status_code == HTTPStatus.OK:
    data = r.json()
    df = pd.json_normalize(data)
df

,id_pedido,data_pedido,status,cliente.id_cliente,cliente.nome_cliente,detalhes_compra.produto.id_produto,detalhes_compra.produto.nome_produto,detalhes_compra.produto.categoria,detalhes_compra.quantidade,detalhes_compra.preco_unitario,detalhes_compra.preco_total
0,21,2025-01-21,Entregue,121,Ursula Castro,221,Sandália Feminina,Calçados,1,90.0,90.0
1,22,2025-01-22,Pendente,122,Victor Andrade,222,Chuteira,Esportes,1,230.0,230.0
2,23,2025-01-23,Entregue,123,Wagner Neves,223,Carregador Portátil,Eletrônicos,1,100.0,100.0
3,24,2025-01-24,Entregue,124,Xavier Almeida,224,Bola de Futebol,Esportes,1,120.0,120.0
4,25,2025-01-25,Cancelado,125,Yasmin Dias,225,Maquiagem Completa,Beleza,1,250.0,250.0