Jorge, ao receber dados relacionados a pedidos feitos na empresa que trabalha, percebeu que alguns dos pedidos não continham uma data de entrega prevista registrada no momento do pedido, deixando valores ausentes no dataset.

Então, ele identificou que isso poderia ter acontecido por algum problema nos agendamentos. Para solucionar esse problema, ele decidiu assumir que os pedidos sem data de entrega herdarão a próxima data prevista no registro. Isso ocorre porque as previsões são frequentemente baseadas em lotes. Considerando isso, como Jorge poderia fazer o preenchimento dos prazos de entrega?

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../../../data/activities_5.csv')

df

   PedidoID Data_Pedido Data_Entrega_Prevista
0       101  2025-01-01            2025-01-05
1       102  2025-01-02                   NaN
2       103  2025-01-03                   NaN
3       104  2025-01-04            2025-01-07
4       105  2025-01-05                   NaN
5       106  2025-01-06                   NaN
6       107  2025-01-07            2025-01-10
7       108  2025-01-08                   NaN
8       109  2025-01-09                   NaN
9       110  2025-01-10                   NaN

In [ ]:
# Preenche valores NaN com o proximo valor da coluna
df.bfill(inplace=True)

df

   PedidoID Data_Pedido Data_Entrega_Prevista
0       101  2025-01-01            2025-01-05
1       102  2025-01-02            2025-01-07
2       103  2025-01-03            2025-01-07
3       104  2025-01-04            2025-01-07
4       105  2025-01-05            2025-01-10
5       106  2025-01-06            2025-01-10
6       107  2025-01-07            2025-01-10
7       108  2025-01-08                   NaN
8       109  2025-01-09                   NaN
9       110  2025-01-10                   NaN